GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/3

###

DELETE http://localhost:3001/api/persons/2

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Ferando",
  "number": 0
}